### PR TITLE
Set b:undo_ftplugin in filetype plugin

### PR DESCRIPTION
**Pull request by dkearns**
- Move did_ftplugin test to head of file
- Set b:undo_ftplugin in filetype plugin

### CODE REVIEW

**Comment by zaid** [comment]
Thank you @dkearns !

**Comment by gerardbm** [comment]
This is causing the following error:

```
"books.rec" 1577L, 25804C
b:undo_ftplugin        setlocal commentstring< iskeyword< tabstop< softtabstop< shiftwidth<
Se ha detectado un error al procesar /home/gerard/.vim/plugged/vim-rec/ftplugin/rec.vim:
línea   55
E15: La expresión no es válida: ..= ' | setlocal foldmethod< foldexpr<'
E488: Caracteres en exceso al final de la línea
b:undo_ftplugin        setlocal commentstring< iskeyword< tabstop< softtabstop< shiftwidth<
línea   82
E15: La expresión no es válida: ..= " | silent! execute 'nunmap <buffer> <localleader>rf'" ..                 " | silent! execute 'nunma
p <buffer> <localleader>rn'" ..                 " | silent! execute 'nunmap <buffer> <localleader>rs'" ..                 " | silent! ex
ecute 'nunmap <buffer> <localleader>rv'" ..                 " | silent! execute 'unmap  <buffer> <localleader>r]'" ..                 "
| silent! execute 'unmap  <buffer> <localleader>r['" ..                 " | silent! execute 'unmap  <buffer> <localleader>r?'"
E488: Caracteres en exceso al final de la línea
b:undo_ftplugin        setlocal commentstring< iskeyword< tabstop< softtabstop< shiftwidth<
línea   88
E15: La expresión no es válida: ..= ' | setlocal omnifunc<'
E488: Caracteres en exceso al final de la línea
```

**Comment by zaid** [comment]
@gerardbm I'll take a look, could you please provide some information on the version of Vim/Neovim that you're using?

**Comment by dkearns** [comment]
That looks to be due to the `..` string concatenation.  We can change that to use the old `.` operator if you want to support older versions of Vim.

**Comment by gerardbm** [comment]
I'm using Vim 8.0.0197 and Neovim v0.3.1-1-g489d32f2b, both under Debian 9.

Yeah, I supposed it was due to the concatenation. I searched it on Google, however I couldn't find any reference. Making it backward compatible would be nice!

Thanks a lot!

**Comment by zaid** [comment]
My preference is to keep this compatible with older versions of Vim/Neovim so I'll have a PR up today to use `.` instead of `..` for the string concatenation.

**Pull request merged**
